### YamlMime:Role 
title: Solutions Architect 
metadata: 
  title: Solutions Architect
  description: Solutions Architect 拥有计算，网络，存储和安全方面的专业知识。 
uid: role.solution-architect  
summary: | 
  Solutions Architect 拥有计算，网络，存储和安全方面的专业知识。
subTitle: Solutions Architect 拥有计算，网络，存储和安全方面的专业知识。
certificationPaths: 
- title: Azure Solutions Architect
  linkedInKeywords: Azure Solutions Architect
  uid: certification-path.azure-solutions-architect 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-solutions-architect
    levels:
    - advanced    
- title: Dynamics 365 Finance and Operations Apps Solution Architect
  linkedInKeywords: Dynamics 365 Finance and Operations Apps Solution Architect
  uid: certification-path.d365-finance-and-operations-apps-solution-architect-expert
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-financials
    levels:
    - intermediate  
  - uid: certification.d365-functional-consultant-manufacturing
    levels:
    - intermediate 
  - uid: certification.d365-functional-consultant-supply-chain-management
    levels:
    - intermediate 
  - uid: certification.d365-finance-and-operations-apps-developer-associate
    levels:
    - intermediate 
  - uid: certification.d365-finance-and-operations-apps-solution-architect-expert
    levels:
    - advanced  
- title: Dynamics 365 + Power Platform Solution Architect
  linkedInKeywords: Dynamics 365 + Power Platform Solution Architect
  uid: certification-path.power-apps-and-d365-solution-architect-expert
  prerequisites: 
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-sales
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-marketing
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-customer-service
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-field-service
    levels:
    - intermediate
  - uid: certification.power-apps-and-d365-solution-architect-expert
    levels:
    - advanced
- title: Power Platform Solution Architect
  linkedInKeywords: Power Platform Solution Architect
  uid: certification-path.power-platform-solution-architect-expert
  prerequisites: 
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.power-platform-functional-consultant-associate
    levels:
    - intermediate
  - uid: certification.power-platform-developer-associate
    levels:
    - intermediate
  - uid: certification.power-platform-solution-architect-expert
    levels:
    - advanced
certifications:
- uid: certification.azure-solutions-architect
  requiredExams:
  - uid: exam.az-303
  - uid: exam.az-304
- uid: certification.d365-finance-and-operations-apps-solution-architect-expert
  requiredExams:
  - uid: exam.mb-700
- uid: certification.power-apps-and-d365-solution-architect-expert
  requiredExams:
  - uid: exam.mb-600
- uid: certification.azure-for-sap-workloads-specialty
  requiredExams:
  - uid: exam.az-120
- uid: certification.power-platform-solution-architect-expert
  requiredExams:
  - uid: exam.pl-600
resources:
- title: Microsoft 培训和认证指南
  description: 通过简明的培训和认证指南探索所有认证。
  href: https://aka.ms/TrainingCertDeck
- title: 培训和认证海报
  description: 通过此培训和认证海报选择成功的道路。
  href: https://aka.ms/traincertposter
- title: 认证支持
  href: ../help.md
  description: 通过 Microsoft Certification 支持论坛获取帮助。论坛主持人将在一个工作日后回应，周一至周五。
